/**
 * Generates src/sim/trig.tables.ts.
 *
 * Run with `pnpm gen:trig`. The output is committed so the simulation never
 * depends on floating point at runtime, and so a change to these tables shows
 * up as a reviewable diff rather than a silent desync.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ONE = 65536;
const SIN_BITS = 12;
const SIN_SIZE = 1 << SIN_BITS; // 4096
const ATAN_BITS = 10;
const ATAN_SIZE = 1 << ATAN_BITS; // 1024

/** Round half away from zero, so the table is symmetric about the origin. */
const q16 = (v: number): number =>
  v >= 0 ? Math.floor(v * ONE + 0.5) : -Math.floor(-v * ONE + 0.5);

const sin: number[] = [];
for (let i = 0; i < SIN_SIZE; i++) {
  sin.push(q16(Math.sin((2 * Math.PI * i) / SIN_SIZE)));
}

// One extra entry so interpolation at the top of the range needs no wrap test.
const atan: number[] = [];
for (let i = 0; i <= ATAN_SIZE; i++) {
  atan.push(q16(Math.atan(i / ATAN_SIZE)));
}

const rows = (values: number[], perRow: number): string => {
  const out: string[] = [];
  for (let i = 0; i < values.length; i += perRow) {
    out.push('  ' + values.slice(i, i + perRow).join(', ') + ',');
  }
  return out.join('\n');
};

const source = `// GENERATED BY tools/gen-trig.ts — DO NOT EDIT.
// Q16.16 trigonometric lookup tables. Regenerate with \`pnpm gen:trig\`.

/** Entries in SIN_TABLE, covering one full turn. */
export const SIN_BITS = ${SIN_BITS};
export const SIN_SIZE = ${SIN_SIZE};

/** sin(2*PI*i / SIN_SIZE) in Q16.16. */
export const SIN_TABLE: Int32Array = new Int32Array([
${rows(sin, 16)}
]);

/** Entries in ATAN_TABLE, covering a ratio of 0..1 inclusive. */
export const ATAN_BITS = ${ATAN_BITS};
export const ATAN_SIZE = ${ATAN_SIZE};

/** atan(i / ATAN_SIZE) in Q16.16, with a duplicated final entry for lerping. */
export const ATAN_TABLE: Int32Array = new Int32Array([
${rows(atan, 16)}
]);
`;

const out = fileURLToPath(new URL('../src/sim/trig.tables.ts', import.meta.url));
writeFileSync(out, source);
console.log(`wrote ${out} (${SIN_SIZE} sine entries, ${ATAN_SIZE + 1} atan entries)`);
