/**
 * Regenerates test/golden/sim.json — the expected hash of the scripted match.
 *
 * Run this ONLY when a milestone deliberately changes the simulation or
 * extends the script, and say so in the commit. An unexplained regeneration is
 * how a desync gets committed.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  SCRIPT,
  SCRIPT_PLAYERS,
  SCRIPT_SEED,
  SCRIPT_TICKS,
  runScriptCheckpoints,
  runScriptHash,
} from '../test/determinism.ts';

const golden = {
  note: 'GENERATED BY tools/gen-sim-golden.ts — regenerate deliberately, never silently.',
  seed: SCRIPT_SEED,
  players: SCRIPT_PLAYERS,
  ticks: SCRIPT_TICKS,
  commands: SCRIPT.length,
  finalHash: runScriptHash(),
  checkpoints: runScriptCheckpoints(100),
};

const out = fileURLToPath(new URL('../test/golden/sim.json', import.meta.url));
writeFileSync(out, JSON.stringify(golden, null, 1) + '\n');
console.log(`wrote ${out}: finalHash=0x${golden.finalHash.toString(16)}`);
