/**
 * Generates test/golden/trig.json: a reference sample of sin, cos and atan2
 * computed in double precision and rounded to Q16.16.
 *
 * The golden file is the *reference*, not a snapshot of our own output — the
 * test asserts the table-driven implementation stays within a stated ULP
 * budget of it, so a broken table is caught even if it is broken consistently.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ONE = 65536;
const q16 = (v: number): number =>
  v >= 0 ? Math.floor(v * ONE + 0.5) : -Math.floor(-v * ONE + 0.5);

const angles: number[] = [];
for (let i = 0; i < 256; i++) {
  // Spread over just over four turns, in both directions, on irregular steps
  // so table entries are not all hit exactly.
  angles.push(q16(((i - 128) * 2 * Math.PI * 4.37) / 256));
}

const sin = angles.map((a) => q16(Math.sin(a / ONE)));
const cos = angles.map((a) => q16(Math.cos(a / ONE)));

const atan2: { z: number; x: number; want: number }[] = [];
for (let i = 0; i < 64; i++) {
  const t = (i / 64) * 2 * Math.PI;
  const r = 1 + (i % 7);
  const x = q16(Math.cos(t) * r);
  const z = q16(Math.sin(t) * r);
  atan2.push({ z, x, want: q16(Math.atan2(z / ONE, x / ONE)) });
}
// Axis-aligned and degenerate cases.
for (const [z, x] of [
  [0, 0],
  [0, ONE],
  [0, -ONE],
  [ONE, 0],
  [-ONE, 0],
  [ONE, ONE],
  [-ONE, -ONE],
]) {
  atan2.push({ z: z as number, x: x as number, want: q16(Math.atan2((z as number) / ONE, (x as number) / ONE)) });
}

const out = fileURLToPath(new URL('../test/golden/trig.json', import.meta.url));
writeFileSync(out, JSON.stringify({ note: 'GENERATED BY tools/gen-trig-golden.ts', angles, sin, cos, atan2 }, null, 1));
console.log(`wrote ${out}`);
