/**
 * The stress profile from M33.
 *
 * Builds the scenario PLAN.md names — a thousand units, active combat, full
 * fog updates — and reports where the tick actually goes. Run with
 * `pnpm stress`; the numbers it prints are the baseline committed in
 * test/golden/perf.json, which the regression test compares against.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { createMatchFromWorld } from '../src/sim/matchinit.ts';
import { stepMatch } from '../src/sim/tick.ts';
import { spawnUnit } from '../src/sim/units.ts';
import { unitTypeById } from '../src/sim/unittypes.ts';
import { setAiPlayer } from '../src/sim/ai.ts';
import { createCostGrid } from '../src/nav/grid.ts';
import { updateFog } from '../src/sim/fog.ts';
import { stepMovement } from '../src/sim/movement.ts';
import { stepCombat } from '../src/sim/combat.ts';
import { rebuildSpatialHash } from '../src/sim/spatialhash.ts';
import { ensureField } from '../src/sim/navcache.ts';
import * as w from '../src/sim/world.ts';
import { ONE, fromInt } from '../src/sim/fixed.ts';
import type { Match } from '../src/sim/match.ts';

const UNITS_PER_SIDE = 500;
const MAP = 256;

export function buildStressMatch(): { match: Match; world: w.World } {
  const world = w.createWorld({ width: MAP, height: MAP });
  world.startLocations.push({ cell: w.cellIndex(world, 40, 128) });
  world.startLocations.push({ cell: w.cellIndex(world, 216, 128) });

  // Terrain with something to path around, and resources to mine.
  for (let y = 40; y < 216; y += 24) {
    for (let x = 60; x < 200; x += 5) {
      w.setFlags(world, w.cellIndex(world, x, y), 0);
    }
  }
  for (const [bx, by] of [
    [46, 128],
    [206, 128],
  ] as const) {
    for (let i = 0; i < 8; i++) {
      const cell = w.cellIndex(world, bx + i, by);
      world.resourceNodes.push({ cell, type: w.ResourceType.Minerals, amount: 100_000 });
      world.flags[cell] = ((world.flags[cell] as number) & ~w.BUILDABLE) | w.VISION_BLOCKER;
    }
  }

  const match = createMatchFromWorld({
    world,
    seed: 0x5712e55,
    playerCount: 2,
    startingMinerals: 5000,
    costGrid: createCostGrid(world),
  });
  setAiPlayer(match, 0, true);
  setAiPlayer(match, 1, true);

  // Two armies that will meet in the middle.
  const types = ['soldier', 'raider', 'siege'] as const;
  for (let i = 0; i < UNITS_PER_SIDE; i++) {
    const type = unitTypeById(types[i % types.length] as string);
    spawnUnit(match.units, {
      type,
      ownerId: 0,
      x: fromInt(70 + (i % 30)) + ONE / 2,
      z: fromInt(110 + ((i / 30) | 0)) + ONE / 2,
    });
    spawnUnit(match.units, {
      type,
      ownerId: 1,
      x: fromInt(160 + (i % 30)) + ONE / 2,
      z: fromInt(110 + ((i / 30) | 0)) + ONE / 2,
    });
  }
  return { match, world };
}

/** Best of `runs` after warming up, in milliseconds. */
function best(runs: number, warmup: number, work: () => void): number {
  for (let i = 0; i < warmup; i++) work();
  let lowest = Infinity;
  for (let i = 0; i < runs; i++) {
    const start = performance.now();
    work();
    lowest = Math.min(lowest, performance.now() - start);
  }
  return lowest;
}

function main(): void {
  const { match, world } = buildStressMatch();
  const context = { world };

  // Let the armies engage before measuring, so combat is actually running.
  for (let i = 0; i < 400; i++) stepMatch(match, [], context);

  let engaged = 0;
  for (let i = 0; i < match.units.count; i++) {
    if (match.units.isAlive[i] === 1 && match.units.targetHandle[i] !== 0) engaged++;
  }

  const grid = match.costGrid!;
  const results = {
    note: 'GENERATED BY tools/stress.ts — the M33 performance baseline.',
    units: match.units.alive,
    engaged,
    mapCells: world.width * world.height,
    tickMs: best(20, 5, () => stepMatch(match, [], context)),
    movementMs: best(20, 5, () => {
      match.spatialHash = stepMovement(match, {
        world,
        grid,
        hash: match.spatialHash,
        field: (goal) => ensureField(match.fields, grid, goal),
      });
    }),
    combatMs: best(20, 5, () => stepCombat(match, context)),
    fogMs: best(20, 5, () => updateFog(match, world)),
    spatialHashMs: best(20, 5, () => {
      match.spatialHash = rebuildSpatialHash(match.spatialHash, match.units);
    }),
  };

  for (const [name, value] of Object.entries(results)) {
    if (typeof value === 'number') {
      console.log(`${name.padEnd(16)} ${name.endsWith('Ms') ? `${value.toFixed(3)} ms` : value}`);
    }
  }

  if (process.argv.includes('--write')) {
    const out = fileURLToPath(new URL('../test/golden/perf.json', import.meta.url));
    writeFileSync(out, JSON.stringify(results, null, 1) + '\n');
    console.log(`\nwrote ${out}`);
  }
}

if (process.argv[1]?.endsWith('stress.ts')) main();
